# ** Common **
spring:
  config:
    activate:
      on-profile: "common"
  web:
    locale: ko_KR
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
# Server
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8